trigger: none
pr:
  branches:
    include:
      - master
      - sumo
jobs:

################################################################################
  - job: sumo
################################################################################
    displayName: sumo
    pool:
      name: azureiotedge
      demands:
        - yocto
    timeoutInMinutes: 360
    steps:
      - script: scripts/fetch.sh sumo
        displayName: Fetch
        env:
          METARUST_REV: 'c72b2dda3a4f70ed257c7de9bedb4b04732970a4'
      - script: scripts/build.sh
        displayName: Build
